--
-- Table structure for table `idiomas`
--
--

INSERT INTO `idiomas` (`id`, `name`, `status`) VALUES
(1, 'Espanhol', true),
(2, 'Inglês', true),
(3, 'Francês', true),
(4, 'Alemão', true),
(5, 'Italiano', true),
(6, 'Português', true),
(7, 'Russo', true),
(8, 'Mandarim', true),
(9, 'Japonês', true),
(10, 'Guaraní', true),
(11, 'Hebraico', true),
(12, 'Gregp', true),
(13, 'Esperanto', true),
(14, 'Holandês', true),
(15, 'Catalão', true),
(16, 'Árabe', true),
(17, 'Vasco', true),
(18, 'Bengalí', true),
(19, 'Armẽnio', true),
(20, 'Tcheco', true),
(21, 'Dinamarquês', true),
(22, 'Finlandês', true),
(23, 'Coreano', true),
(24, 'Noruego', true),
(25, 'Polaco', true),
(26, 'Quechua', true),
(27, 'Romano', true),
(28, 'Sérvio', true),
(29, 'Esloveno', true),
(30, 'Sueco', true),
(31, 'Tailandês', true),
(32, 'Turco', true),
(33, 'Ucraniano', true),
(34, 'Vietnamita', true),
(35, 'Búlgaro', true),
(36, 'Albanês', true),
(37, 'Hindi', true),
(38, 'Galego', true),
(39, 'Islandẽs', true),
(40, 'Indonésio', true);
